### ISSUE TITLE
Minimum GitHub permissions

### ISSUE THREAD

**Issue by adkerr** [justwatchcom/github-releases-notifier#4]
Do you have a list of which permissions are required for the GitHub API token?

Thanks!

**Comment by metalmatze** [comment]
I am running this with only the ` public_repo` scope under repo. 
So that should be enough :wink:

**Comment by adkerr** [comment]
Thanks. That’s what I guessed but it’s nice to have confirmation.

**Comment by dominikschulz** [comment]
Thanks for confirming @metalmatze

**Comment by tommyblue** [comment]
I'd drop a line in the README, it's not obvious which permissions are required 😄
