### ISSUE TITLE
can't find any releases for hashicorp/consul

### ISSUE THREAD

**Issue by mhumeSF** [justwatchcom/github-releases-notifier#6]
Awesome tool! Literally stumbled on it when I was searching for something that would monitor releases of gopass. I have this error for a couple of repo's I am following. Is there a standard in the way projects should list releases in order to be followed correctly? Or is this just a warning?

**Comment by metalmatze** [comment]
Yes. This tool can't send notifications for projects that don't create a GitHub release. If they only tag a new release with git, this is not annotated with enough information in GitHub's API, unfortunately.
